### PR TITLE
Fix message format

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
May I ask for review, please?

**Comment by pzygielo** [comment]
@cushon, @graememorgan - may I ask for review, please?

**Comment by pzygielo** [comment]
@cushon, @graememorgan - may I ask for review, please?

**Comment by graememorgan** [comment]
Sorry for the late review. I cloned this internally and added a regression test.

Thanks for the fix! I'm surprised this went unnoticed so long. :)

**Comment by pzygielo** [comment]
Thanks for checking, Graeme.

**Pull request closed without merging**
