### PR TITLE
Moe Sync

### PR DESCRIPTION
**Pull request by ronshapiro**
This code has been reviewed and submitted internally. Feel free to discuss on the PR and we can submit follow-up changes as necessary.

Commits:
=====
<p> Fix handling of implicit lambda parameters in IterablePathParameter

RELNOTES: N/A

cd4de77fd629e24aaa0278ae32c126a351782b3c

-------

<p> Change TargetTypeScanner from a TreeScanner to a SimpleTreeVisitor.

This scanner should only be considering the parent tree itself. If TreeScanner is used and the type of the parent node is not explicitly handled, the scanner will descend into child nodes of that parent, and then base the return value on some arbitrary node. A SimpleTreeVisitor will return the default value, null.

RELNOTES: Fix AssertionError arising from ASTHelpers.targetType descending into AST for unhandled nodes.

2c7e3962628cadb6b08989fbd8c74841cbb2899c

-------

<p> Reformat with the latest version of google-java-format

RELNOTES: N/A

542a7f8e20a416ebbdb38cf91d2156db272fb1db

-------

<p> Update RestrictToEnforcer to allow new Support Library packages

RELNOTES: None

f7dda3c157ae6ab9ed3ba9ae264e352f5b0c17a7

-------

<p> Internal change

RELNOTES: N/A

806468839fae040a951072a38a22cc0eadfea41c

-------

<p> Accept type variables that have a thread-safe upper bound as thread-safe types.

RELNOTES: N/A

d866001cc6a881868ae33b276657d8b0fff24413

-------

<p> Use collectors.joining as per https://github.com/google/error-prone/pull/964#pullrequestreview-104413409 (@jbduncan)

RELNOTES: n/a

f555955391aea96cb3eb4cf51444f97defc4685a

-------

<p> Ensure the return values of java.util.Arrays APIs are used in some way

Partially fixes https://github.com/google/error-prone/issues/810

RELNOTES: Add java.util.Arrays to ReturnValueIgnored check

RELNOTES=Add java.util.Arrays to ReturnValueIgnored check

bf3a1ffbee78ab4d598799a09964cfdec8684046

### CODE REVIEW

**Comment by eaftan** [comment]
@ronshapiro, is the CLA bot complaining because the mention of jbduncan?

**Comment by cushon** [comment]
The bot should only be looking at commit authors. I don't see any commits without CLAs.

**Comment by ronshapiro** [comment]
No, for some reason it's getting confused over @kluever (on a couple of repositories, not just ErrorProne). The team is looking into it.

**Comment by ronshapiro** [comment]
I think it's fine to merge - they're aware of the bug

**Pull request merged**
