### PR TITLE
check When value for CheckReturnValue annotation

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by ellisjoe** [comment]
I signed it!

**Comment by ellisjoe** [comment]
based on the failing test `noCRVonClasspath` it seems like this may not be a desired feature since this requires having `jsr305` available at compile time. Would be great to hear if this is worth pursuing more.

**Comment by eaftan** [comment]
What's the use case for setting the `when` property of `@CheckReturnValue` to anything other than `ALWAYS`?

**Comment by ellisjoe** [comment]
we have ping endpoints that looks like:
```
@CheckReturnValue(when = When.NEVER)
String ping();
```

**Comment by cushon** [comment]
We created a [`@CanIgnoreReturnValue`](http://errorprone.info/api/latest/com/google/errorprone/annotations/CanIgnoreReturnValue.html) annotation that has the same behaviour. Maybe we weren't aware of `when` at the time?

**Comment by ellisjoe** [comment]
how do you feel about supporting both `@CanIgnoreReturnValue` and `when`?

**Comment by eaftan** [comment]
Do other tools respect the when property?  If so, which ones?

`@CheckReturnValue(when = When.NEVER)` seems to say that you should *never* consume the result of the call, which is weird.

**Comment by cushon** [comment]
I think we're going to stick with `@CanIgnoreReturnValue` for now. The Error Prone `@CRV` annotation doesn't support `when`, and the JSR-305 annotations have an [uncertain future](https://github.com/google/guava/issues/2960).

**Pull request closed without merging**
