### PR TITLE
Feature/refactoring experiment

### PR DESCRIPTION
**Pull request by ameyaKetkar**
This module, parses the source code to collect data for ProtoBuff, which will further be utilized for analysis.

### CODE REVIEW

**Comment by ameyaKetkar** [comment]
I signed it!

**Comment by jbduncan** [comment]
@ameyaKetkar, I can't speak for the Error Prone team, but it's not clear to me what this PR is aiming to do... :thinking: 

Can you clarify things for me?

**Comment by ameyaKetkar** [comment]
@jbduncan I am attempting to develop a refactoring tool using error prone to specialise usage of functional interfaces with @eaftan and @amesbah . This is some experimental code to check feasibility.

**Comment by jbduncan** [comment]
Oh, that sounds cool! Thanks for the clarification. :)

**Pull request closed without merging**
