### PR TITLE
Support other file encodings than UTF-8

### PR DESCRIPTION
**Pull request by pskiwi**
The source file encoding _UTF-8_ is hard coded into [MaskedClassLoader.java](https://github.com/google/error-prone/blob/71f27667eb723c18e574f905e0fe3a64786a2c3c/check_api/src/main/java/com/google/errorprone/MaskedClassLoader.java#L67). 
This makes it impossible to use error-prone for otherwise encoded sources.
This MR leaves the default to _UTF-8_ and only changes it if the parameter "-encoding" is given on the command line.

This problem ist reported in #873  and mentioned in https://groups.google.com/d/msg/error-prone-discuss/075NR0aTzm4/LsHe6t7BBgAJ.

### CODE REVIEW

**Comment by pskiwi** [comment]
I signed it!

**Comment by pskiwi** [comment]
I signed it!

**Comment by jbduncan** [comment]
@pskiwi I think that the email address you used to sign your commits is different to your GitHub email address. The reason I think this is because if you used the same email address in both places, you'd see your GitHub username under each commit, in a similar fashion to this:

capture2

However, in this case, we just see your real name instead:

capture

Have you checked and updated your Git settings as per [the instructions in the Git book](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup) to make sure that the email address you registered on your local installed copy of Git is the same as your GitHub email address?

**Comment by jbduncan** [comment]
Oops, never mind, too quick for my own good! Looks like you fixed things on your end, so please feel free to disregard my earlier comment. :)

**Comment by pskiwi** [comment]
I will start a new MR with fixed email addresses.

**Pull request closed without merging**
