### PR TITLE
Unbreak Travis build

### PR DESCRIPTION
**Pull request by eaftan**

### CODE REVIEW

**Comment by Stephan202** [comment]
There's a [comment thread](https://github.com/travis-ci/travis-ci/issues/9368#issuecomment-405035447) related to the `openjdk10` [build failure](https://travis-ci.org/google/error-prone/jobs/443465948). In this particular case the issue is triggered when attempting to download `junit:junit:jar:4.13-SNAPSHOT` from the Sonatype Nexus Snapshots repository.

(Just leaving this comment here in case others building on top of Error Prone hit the same issue. But this may be a good opportunity to ask: are there plans to replace that SNAPSHOT dependency with a released artifact?)

**Comment by cushon** [comment]
@Stephan202 thanks--I think we're seeing the same issue. I'm testing a work-around in #1162.

> are there plans to replace that SNAPSHOT dependency with a released artifact?

https://github.com/junit-team/junit4/issues/1496 :)

**Comment by cushon** [comment]
I fixed it in 7afde3efa95084147e36fcbf4c4b98f2a7e4d1c3.

**Comment by Stephan202** [comment]
@cushon hah, feeling your pain; I opened a post-4.12 PR nearly four years ago (junit-team/junit4#1054) :).

(But at this point Google may consider migrating to the more active JUnit 5 development?)

**Pull request closed without merging**
