### PR TITLE
Target annotations for Java 6

### PR DESCRIPTION
**Pull request by trask**
Hi!

I'm hoping you will consider this PR to target (just the) annotations for Java 6 (instead of the current target of Java 7).  The issue is that the error prone annotations are now used in recent guava versions (which still supports Java 6), and this can cause issues for some libraries (e.g. Jackson json library) which reflect on guava's annotations (e.g. see exception below).  This is easily solved by not including the error prone annotations at runtime (and normally they are not included at runtime since guava marks them as an optional dependency), but unfortunately the annotations must be included at runtime in order to support IBM Java 6 SR8 and prior due to http://www-01.ibm.com/support/docview.wss?uid=swg1IZ76354.  Let me know if this convinces you of the benefit of this PR or if we can discuss this further.  Thanks.

```
com/google/errorprone/annotations/concurrent/LazyInit : Unsupported major.minor version 51.0
java.lang.UnsupportedClassVersionError: com/google/errorprone/annotations/concurrent/LazyInit : Unsupported major.minor version 51.0
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:181)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1014)
	at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:1007)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._constructField(AnnotatedClass.java:826)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:706)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:692)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveFields(AnnotatedClass.java:475)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:284)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:350)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:283)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:169)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:222)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:348)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildMapSerializer(BasicSerializerFactory.java:764)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.buildContainerSerializer(BasicSerializerFactory.java:573)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:194)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:153)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1203)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1176)
	at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:606)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:72)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:854)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:671)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2383)
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2515)
```

### CODE REVIEW

**Comment by cpovirk** [comment]
A couple comments (as someone more involved with Guava than with Error Prone):

- Guava 20.0 is the last version of Guava to support Java 6. (You might already be aware of this; I just wanted to state it explicitly -- and go improve [our docs](https://github.com/google/guava/wiki/Release21) while I'm at it.)
- But even Guava 20.0 depends on a Java-7 version of `error_prone_annotations`. (As far as I can tell, *all* versions of `error_prone_annotations` are built for Java 7 -- except for [a couple that were built for Java 8 before that was fixed](https://github.com/google/guava/issues/2646#issuecomment-266454833).) I guess that we got away with this because, as you say, Guava omits the annotations at runtime by default. (We [changed that](https://github.com/google/guava/issues/2855) in Guava 22.0, but since that version requires Java 7, anyway, it doesn't introduce compatibility problems.)

Now I don't know what the pros and cons of this are for Error Prone, but I wanted to record all that somewhere.

**Comment by trask** [comment]
Hi @cpovirk, thanks for these details.  It's helpful to know that Java 6 support is never coming back in Guava.  In this case, I will probably just roll back from Guava 20 to Guava 18, before the Java 7 error prone annotations were introduced.

**Comment by eaftan** [comment]
@trask We'll close this PR then, since you're planning to roll back your Guava version.

**Comment by trask** [comment]
Hi @eaftan, I just tried rolling back to Guava 18, but I also use gRPC (which still supports Java 6), and depends on Guava 19.  Any chance to reconsider?  Thanks.

**Pull request closed without merging**
