### PR TITLE
Moe sync

### PR DESCRIPTION
**Pull request by ronshapiro**

### CODE REVIEW

**Comment by jbduncan** [comment]
Hmm, what is "JCL" a reference to in the commit message of https://github.com/google/error-prone/pull/911/commits/7411129cc47262a834658878236952aaa109331c? :thinking:

**Comment by ronshapiro** [comment]
"Java Core Libraries"

**Comment by jbduncan** [comment]
Thanks @ronshapiro. :)

**Comment by JakeWharton** [comment]
"JCL libraries" like "ATM machines"

**Pull request merged**
