### PR TITLE
Stop ignoring everything under .idea

### PR DESCRIPTION
**Pull request by tom-smalls**
As a developer who doesn't work at Google, it is hard to work on error prone (and create pull requests) without violating your styling rules as the project code codeStyleSettings.xml is not commited to GitHub.

By not ignoring everything under .idea this will be possible to do, and make external developer's lives easier.

If this is accepted can someone from Google the correct xml files?

Thanks,

Tom

### CODE REVIEW

**Comment by eaftan** [comment]
It looks like we do have a projectCodeStyles.xml file committed:
https://github.com/google/error-prone/blob/master/.idea/projectCodeStyle.xml

It's just that it's wrong.  I'll add the correct one.

**Comment by cushon** [comment]
Also un-ignoring `.idea` sounds reasonable. I think added the suppression to avoid churn when working on different machines / intellij versions.

@tom-smalls - can you add a reference for where the list of files came from? Was it adapted from something like https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore?

**Comment by tom-smalls** [comment]
It's just what we use at work to be perfectly honest

**Comment by tom-smalls** [comment]
It's what we use at work to be honest, although I believe it is based on http://devnet.jetbrains.net/docs/DOC-1186

Shall I close the pull request? Seems to have brought in a load of other changes, bit annoying.

**Comment by cushon** [comment]
Fair enough, I was just curious. I squashed the commits and pushed as 72bd09a5a52f92be7d3bd3e5595b3b6550b5c6fe.

Thanks!

**Pull request closed without merging**
