### PR TITLE
Allow external compiler launch from Ant

### PR DESCRIPTION
**Pull request by garricko**
Forked execution of the compiler is more compatible for some projects,
and avoids having to place the error_prone_ant.jar file in your local
Ant install directory (it can be checked in, downloaded, etc.).

### CODE REVIEW

**Comment by cushon** [comment]
@garricko - I'm sorry we lost track of this pull request. Is this something you're still interested in contributing?

Since you opened the PR, we finally did another release and the ant plugin got re-arranged a bit.

**Comment by garricko** [comment]
I think it still makes sense to have an external launcher, since that allows you to control things (like memory) that are off-limits for in-process compilers. I rebased to the latest code and added a few improvements.

**Comment by cushon** [comment]
Agreed, it'd be good to support.

Something funny happened to the rebase, though: e4642135594d128c7aae1af4121e141a96180eea and bd9b73f5e167c6cfb07bfb16b2cb70d5537dab9b ended up on either side of all the other patches.

Also, can you please fill out a [CLA](https://github.com/google/error-prone/blob/master/CONTRIBUTING.md)?

**Comment by garricko** [comment]
I couldn't figure out how to fix that rebase mess, so I created a new pull request 293 and am closing this one. I filled out the CLA as requested.

**Comment by cushon** [comment]
Thanks, SGTM

**Pull request closed without merging**
